version: "3"

dotenv: [".env"]

tasks:
  build:
    cmds:
      - go build

  lint:
    cmds:
      - golangci-lint run ./...

  test:
    deps: [build]
    cmds:
      - npx --yes @hashgraph/hedera-local@v2.14.0 start -d --network local
      - defer: npx --yes @hashgraph/hedera-local@v2.14.0 stop
      - go test -v ./...
