version: "3"
vars:
  HEDERA_LOCAL_VERSION: v2.14.0

dotenv: [".env"]

tasks:
  build:
    cmds:
      - go build

  lint:
    cmds:
      - golangci-lint run ./...

  "hedera:start":
    cmds:
      - npx --yes @hashgraph/hedera-local@{{ .HEDERA_LOCAL_VERSION }} start -d --network local

  "hedera:stop":
    cmds:
      - npx --yes @hashgraph/hedera-local@{{ .HEDERA_LOCAL_VERSION }} stop

  test:
    deps: [build, "hedera:start"]
    cmds:
      - defer: { task: "hedera:stop" }
      - go test -v ./...
