version: "3"

tasks:
  build:
    cmds:
      - go build cmd/

  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - hedera start -d -n local
      - go test ./...
      - hedera stop
