name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.20.6
      - name: Run go vet
        run: go vet ./...
      - name: Run go build
        run: go build -v ./...
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.17.0
      - name: Install @hashgraph/hedera-local
        run: npm install @hashgraph/hedera-local@v2.11.3 -g
      - name: Start hedera-local
        run: hedera start -d
      - name: Run go test
        run: go test -v ./...
      - name: Stop hedera-local
        if: always()
        run: hedera stop
