name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      HEDERA_NODE_VERSION: 2.14.0
      NETWORK: local
      OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
      OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.1
      - name: Install Task
        uses: arduino/setup-task@v1.0.3
      - name: Set up Node
        uses: actions/setup-node@v3.8.1
        with:
          cache: npm
          cache-dependency-path: .github/workflows/ci.yml
          node-version: 20.7.0
      - name: Run go vet
        run: go vet ./...
      - name: Run go test
        run: task test
